// ui-next/src/components/home/Carousel.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import Flickity from "flickity";
  import "flickity-fullscreen";
  import "flickity-fullscreen/fullscreen.css";
  import "flickity-imagesloaded";
  import { Resize } from "@cloudinary/url-gen/actions";
  import info from "@/info.json";
  import cld from "@/utils/cloudinary";

  const { carousel } = info.home.photography;

  const images = carousel.map(c =>
    cld.image(c).resize(Resize.scale("auto")).toURL(),
  );

  onMount(() => {
    new Flickity(".carousel", {
      wrapAround: true,
      autoPlay: true,
      lazyLoad: true,
      imagesLoaded: true,
      pageDots: false,
      cellAlign: "center",
      // @ts-ignore
      fullscreen: true,
    });
  });
</script>

<div class="carousel overflow-hidden">
  {#each images as img}
    <img src={img} class="absolute inset-0 block rounded-2xl px-2" />
  {/each}
</div>

// ui/src/components/home/whatIDo/Carousel.tsx
import { useState } from "react";
import SwipeableViews from "react-swipeable-views";
import { autoPlay } from "react-swipeable-views-utils";

import { Resize } from "@cloudinary/url-gen/actions/resize";
import { MobileStepper } from "@mui/material";

import cld from "../../../api/cloudinary";
import carouselData from "./carouselData.json";

const AutoPlaySwipeableViews = autoPlay(SwipeableViews);

function Carousel() {
  const [activeStep, setActiveStep] = useState(0);
  const images = carouselData.map(c => ({
    publicId: c,
    url: cld.image(c).resize(Resize.scale().width("auto")).toURL(),
  }));

  return (
    <div>
      <AutoPlaySwipeableViews
        axis="x"
        className="m-0 rounded-2xl p-0"
        index={activeStep}
        onChangeIndex={step => setActiveStep(step)}
        enableMouseEvents
      >
        {images.map((c, i) => (
          <div key={c.publicId}>
            {Math.abs(activeStep - i) <= 2 ? (
              <img
                src={c.url}
                alt={c.publicId}
                className="block h-auto w-full overflow-hidden"
              />
            ) : null}
          </div>
        ))}
      </AutoPlaySwipeableViews>
      <MobileStepper
        variant="dots"
        backButton={null}
        nextButton={null}
        steps={images.length}
        position="static"
        activeStep={activeStep}
        className="flex place-content-center bg-transparent"
        sx={{
          "& .MuiMobileStepper-dot": {
            "backgroundColor": "rgba(255, 255, 255, 0.5)",
            "zIndex": 10,
            "mt": -6,
            "&.MuiMobileStepper-dotActive": {
              backgroundColor: "primary.main",
            },
          },
        }}
      />
    </div>
  );
}

export default Carousel;
