// src/components/home/what-i-do/before-after.tsx
import BeforeAfterSlider from "react-before-after-slider-component";
import "react-before-after-slider-component/dist/build.css";
import { Resize } from "@cloudinary/url-gen/actions";
import cld from "@/utils/cloudinary.client";

export function BeforeAfter() {
  const imgBefore = cld
    .image("svip/186/7-ImageSegment/cancer")
    .resize(Resize.scale().width("auto"));
  const imgAfter = cld
    .image("svip/186/7-ImageSegment/cancer_otsu")
    .resize(Resize.scale().width("auto"));

  return (
    <BeforeAfterSlider
      className="rounded-2xl"
      firstImage={{ imageUrl: imgAfter.toURL(), alt: "cancer otsu" }}
      secondImage={{ imageUrl: imgBefore.toURL(), alt: "cancer" }}
      delimiterIconStyles={{
        border: "3px solid #818cf8",
      }}
      currentPercentPosition={33}
    />
  );
}

// ui-next/src/components/home/whatIDo/BeforeAfter.svelte
<script lang="ts">
  import cld from "@/utils/cloudinary.ts";
  import { Resize } from "@cloudinary/url-gen/actions";
  import * as juxtapose from "juxtaposejs/build/js/juxtapose.min.js";
  import "juxtaposejs/build/css/juxtapose.css";
  import { onMount } from "svelte";

  const before = cld
    .image("svip/186/7-ImageSegment/cancer")
    .resize(Resize.scale().width("auto"))
    .toURL();
  const after = cld
    .image("svip/186/7-ImageSegment/cancer_otsu")
    .resize(Resize.scale().width("auto"))
    .toURL();

  onMount(() => {
    new juxtapose.JXSlider(
      "#juxtapose",
      [
        {
          src: before,
          label: "before",
        },
        {
          src: after,
          label: "after",
        },
      ],
      {
        animate: true,
        showLabels: false,
        showCredits: false,
        startingPosition: "30%",
        makeResponsive: true,
      },
    );
  });
</script>

<div id="juxtapose" class="juxtapose" />
