// ui/src/components/shared/Navbar.tsx
import { useEffect, useRef, useState } from "react";
import { Link, useLocation } from "react-router-dom";

import { Resize } from "@cloudinary/url-gen/actions/resize";
import { Box, Button, Menu, MenuItem, useScrollTrigger } from "@mui/material";

import cld from "../../api/cloudinary";
import { cn } from "../../utils";

// const DARK_LOGO = cld.image("logo/logo-black").resize(Resize.scale()).toURL();

const LIGHT_LOGO = cld.image("logo/logo-white").resize(Resize.scale()).toURL();

const SCROLL_THRESHOLD = 30;

const NAV_LINKS = [
  { path: "/", label: "Home" },
  { path: "/about", label: "About/CV" },
];

const PORTFOLIO_LINKS = [
  { path: "/dev", label: "Software" },
  { path: "/photography", label: "Photography" },
  { path: "/svip", label: "Coursework" },
];

function Navbar() {
  const location = useLocation();
  const [anchorEl, setAnchorEl] = useState<HTMLElement | null>(null);
  const headerRef = useRef<HTMLElement>(null!);
  const isPastScrollThreshold = useScrollTrigger({
    disableHysteresis: true,
    threshold: SCROLL_THRESHOLD,
    target: window ? window : undefined,
  });
  const isHomepage = location.pathname === "/";

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [location.pathname]);

  return (
    <>
      <header
        className={cn("z-10 w-full", {
          fixed: isHomepage,
        })}
        ref={headerRef}
      >
        <nav
          className={cn(
            "mb-10 bg-gradient-to-r from-indigo-950 to-purple-900 px-12 transition-all duration-300 ease-in-out",
            {
              "m-8 rounded-[50px] py-2": !isPastScrollThreshold && isHomepage,
            },
          )}
        >
          <div className="flex">
            <div className="flex flex-auto items-center">
              <Link to="/">
                <img
                  src={LIGHT_LOGO}
                  alt="logo"
                  className={cn(
                    "h-[50px] opacity-0 transition-all duration-300 ease-in-out",
                    {
                      "opacity-1 my-2 h-[70px]": isHomepage
                        ? isPastScrollThreshold
                        : true,
                    },
                  )}
                />
              </Link>
            </div>
            <div className="flex flex-auto items-center justify-end">
              {NAV_LINKS.map(nav => (
                <Link to={nav.path} key={nav.path}>
                  <Button
                    disableRipple
                    variant="text"
                    className="section-header text-white"
                    size="large"
                  >
                    {nav.label}
                  </Button>
                </Link>
              ))}
              <Button
                disableRipple
                variant="text"
                className="section-header text-white"
                onClick={e => setAnchorEl(e.currentTarget)}
                size="large"
              >
                Portfolio
              </Button>
            </div>
          </div>
        </nav>
      </header>

      <Menu
        open={!!anchorEl}
        anchorEl={anchorEl}
        onClose={() => setAnchorEl(null)}
        elevation={6}
        anchorOrigin={{
          vertical: "bottom",
          horizontal: "right",
        }}
        transformOrigin={{
          vertical: "top",
          horizontal: "right",
        }}
        PaperProps={{
          className: "rounded-2xl bg-purple-900",
        }}
      >
        {PORTFOLIO_LINKS.map(port => (
          <Box
            key={port.path}
            component={Link}
            to={port.path}
            className="section-header text-white"
          >
            <MenuItem
              onClick={() => setAnchorEl(null)}
              disableRipple
              className="flex place-content-end"
            >
              {port.label}
            </MenuItem>
          </Box>
        ))}
      </Menu>
    </>
  );
}

export default Navbar;

// ui/src/components/common/svelte/Navbar.svelte
<script lang="ts">
  import { Resize } from "@cloudinary/url-gen/actions";
  import cld from "@/utils/cloudinary.ts";
  import { onMount } from "svelte";

  const LIGHT_LOGO = cld
    .image("logo/logo-white")
    .resize(Resize.scale().width("auto"))
    .toURL();

  const NAV_LINKS = [
    { path: "/", label: "Home" },
    { path: "/about", label: "About/CV" },
  ];

  const PORTFOLIO_LINKS = [
    { path: "/photography", label: "Photography" },
    { path: "/dev", label: "Software" },
    { path: "/svip", label: "Video/Image Processing" },
  ];

  let isHome = true;

  $: isHome = window.location.pathname === "/";

  onMount(() => {
    const header = document.querySelector("header")!;
    if (isHome) header.style.position = "fixed";
  });
</script>

<header class="z-10 w-full">
  <nav
    class="navbar bg-gradient-to-r from-indigo-950/25 to-slate-900/25 px-12 backdrop-blur-md transition-all duration-300 ease-in-out"
  >
    <div class="flex flex-auto items-center">
      <a href="/">
        <img
          src={LIGHT_LOGO}
          alt="logo"
          class="opacity-1 my-2 h-[70px] w-auto transition-all duration-300 ease-in-out"
        />
      </a>
    </div>

    <ul
      class="section-header hidden flex-auto items-center justify-end gap-6 md:menu md:menu-horizontal md:visible md:flex"
    >
      {#each NAV_LINKS as nav}
        <li>
          <a href={nav.path}>
            <span class="text-white">
              {nav.label}
            </span>
          </a>
        </li>
      {/each}
      <li>
        <details>
          <summary>Portfolio</summary>
          <ul>
            {#each PORTFOLIO_LINKS as port}
              <li>
                <a href={port.path}>
                  <span class="text-white">
                    {port.label}
                  </span>
                </a>
              </li>
            {/each}
          </ul>
        </details>
      </li>
    </ul>
  </nav>
</header>
